name: Contributions
on:
  schedule:
      # every 12 hours
    - cron: "0 */6 * * *"
    
  workflow_dispatch:
  push:
    branches:
    - main

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

    # Generates the snake  
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: pravin435916
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}